### ISSUE TITLE
First Person Corruption

### ISSUE THREAD

**Issue by Fyoncle** [0ql/kaffees_dual_ride#5]
When your friend sits in the same horse with you and you jump, in the first person your horse clipping into your head which is so annoying, i use Elysium Days Modpack but pretty sure its happens bc of dual ride because when my friend leaves the horse and i jump with the horse then my screen doesnt get corrupted by the horse's head.

**Comment by 0ql** [comment]
Fixed with 56d3def8afc73803ba62fbb2581dc9bb75c46b2c.
